#!/usr/bin/env bash

# desc: re-generate repo documentation

source $CLAMITY_ROOT/lib/_.sh || exit 1

function create_shell_doc_components {
	echo "## Libraries" >/tmp/toc$$
	/bin/rm -f /tmp/body$$
	for lib in (cd $CLAMITY_ROOT/lib; ls *.sh); do
		echo "* **$lib** - `grep '^# desc:' $lib`" >>/tmp/toc$$
	done
}

function print_shell_doc {
	echo -e "# SHell Functions Reference\n\n"
	cat /tmp/toc$$
	echo -e "\n\n"
	cat /tmp/body$$
}

_echo "Updating clamity docs..."
create_shell_doc_components && print_shell_doc >$CLAMITY_ROOT/docs/shell-libraries.md && /bin/rm -f /tmp/toc$$ /tmp/body$$ || exit 1

exit 0
