#!/bin/bash

# desc: overload the TF apply sub-command to record results

source $CLAMITY_ROOT/lib/_.sh || exit 1
source $CLAMITY_ROOT/cmds/tfm.d/shared-funcs.sh || return 1

tf_var_debug_val="$TF_VAR_debug"
[ -n "$TF_VAR_debug" ] && _echo "unsetting TF_VAR_debug for apply. Will reset after" && unset TF_VAR_debug

_run terraform apply "$@" && _tfm_record_results
[ -n "$tf_var_debug" ] && _vrun export TF_VAR_debug=true
