#!/usr/bin/env bash

# desc: CI/CD processing

source $CLAMITY_ROOT/lib/_.sh || exit 1

function common_usage {
	_echo "usage: clamity tfm cicd { complete [-reconfigure] }"
}

function complete_run {
	local mod
	[ ! -x $TFM_REPO_ROOT/.clamity/config/module-sequence.sh ] && echo "$TFM_REPO_ROOT/.clamity/config/module-sequence.sh not found or executable" && return 1
	cd $TFM_REPO_ROOT || return 1
	for mod in $($TFM_REPO_ROOT/.clamity/config/module-sequence.sh); do
		cd $TFM_REPO_ROOT/state-groups/$mod || return 1
		_echo "Processing $(pwd)"
		[ -f .terraform/terraform.tfstate -a \( $ReInit -eq 1 \) ] && { _run run-clamity tfm init -reconfigure || return 1; }
		[ ! -f .terraform/terraform.tfstate ] && { _run run-clamity tfm init || return 1; }
		_run run-clamity tfm plan || return 1
	done
	_echo "Complete execution successful"
	return 0
}

[ -z "$1" ] && common_usage && exit 1
subcmd="$1" && shift

# _set_standard_options "$@"
echo "$@" | grep -q '\-reconfigure' && ReInit=1 || ReInit=0

tf_var_debug_val="$TF_VAR_debug"
[ -n "$TF_VAR_debug" ] && _echo "unsetting TF_VAR_debug for cicd. Will reset after" && unset TF_VAR_debug

ec=0
case "$subcmd" in
complete)
	# disable debug
	complete_run || ec=1
	;;
*) common_usage && exit 1 ;;
esac

[ -n "$tf_var_debug" ] && _vrun export TF_VAR_debug="$tf_var_debug"
exit $ec
