#!/bin/bash

echo not ready yet
return 1

tfmOpts="$1"
shift
source $TFM_REPO_ROOT/tfm-helper.sh -silent || exit 1

cd $TFM_REPO_ROOT
echo "Top level root isolation:"
ls $TFM_ROOT_MODS|grep -v README
echo
