#!/usr/bin/env bash

# desc: normalized interfaoce for CI/CD automation

source $CLAMITY_ROOT/lib/_.sh || exit 1

function local_man_page {
	_usage "$@"
	echo "ABSTRACT

	The cicd cmd is for automation associated with CI/CD pipelines.
"
	return 0
}

# describe sub-commands implemented here (not in external scripts)
customCmds=""
# customCmds="
# \n\tcheck - probe OS for config & environment info
# \n\tpm - power management
# "

subcmd="$1"
[ -z "$subcmd" ] && _usage "`basename $0`" "$customCmds" && exit 1
[ "$subcmd" == help ] && local_man_page `basename $0` "$customCmds" && exit 1
shift

case "$subcmd" in
	# check) check_os "$@" || exit 1;;
	*) _run_clamity_cmd "$CLAMITY_ROOT/cmds/`basename $0`.d" "$subcmd" "$@" || exit 1;;
esac
exit 0
