#!/usr/bin/env bash

# desc: clamity man page

source $CLAMITY_ROOT/lib/_.sh || exit 1

# ---------------------------------------------------------------------------
# Define content for brief help and the manpage for this command. Comment out
# any that does not apply. The formatting of the strings is important to
# maintain - shell data handling is simplistic.
# ---------------------------------------------------------------------------

# More descriptive overview of the command. Paragraph(s) allowed. This is
# included on a man page. (REQUIRED)
__Abstract="
	clamity is a collection of tools for software development, CI/CD
	pipeline automation and operations. The CLI provides an abstracted
	interface with contextual help to ease the cognative load that comes
	with the plethora of platform commands.

	The clamity CLI entry point is implemented as a shell function so it
	can manipulate the current shell environment. Use 'run-clamity' if
	including its commands in scripts. Default settings are stored in a
	file and will apply globally to all your shells running clamity
	whereas non-default (local) settings apply solely to the one shell.

	Local settings and data are stored in \$CLAMITY_HOME (defaults to
	\$HOME/.clamity).

	The clamity user guide can be found at https://user-guide.clamity.com/
"

# one or more lines detailing usage patterns (REQUIRED)
__Usage="
	clamity help
	clamity { command [sub-command] [options] [[--] positional args]
"

# Don't include common options here
# __CommandOptions="
# 	--opt-a
# 		No additional arg. boolean. Use _is_true() and _is_false() funcs
# 		to evaluate.

# 	--opt-name <name>
# 		the name of the thing you specifed using --opt-name.
# "

# For commands that have their own special env vars, inlude this section in
# the man page.
__EnvironmentVariables="
	These are set when clamity is loaded. You can pre-define CLAMITY_HOME
	if you don't want it to be '\$HOME/.clamity'.

	CLAMITY_ROOT (read-only)
		clamity software directory. This is set when clamity is loaded.

	CLAMITY_HOME
		clamity home dir holds logs, customizations, python virtual env,
		and much more. It is created when clamity is loaded for the first
		time. Unless this variable is set, it will be ~/.clamity.

	CLAMITY_<lower-case-option-name>
		Clamity options are managed using 'clamity config'. Options are
		stored as environment variables prefixed with 'CLAMITY_'.
"

# Optional pre-formatted section inserted towards end before Examples
__CustomSections="BOOLEAN EVALUATION

	Bpolean truthiness defines 'false' as an empty string or a case insensitive
	match to anything matching to 'n|no|0|null|none|undefined|undef|f|false'.
	The 'lib/_.sh:_is_false()' shell function is the source of truth for
	truthiness.

SUPPORTED SHELLS

	bash, zsh
"

# Showing examples for comman tasks proves to be very useful in man pages.
__Examples="
	Run 'clamity' or 'clamity help' to get started.

	Update clamity software.

		clamity selfupdate

	Check out the OS environment and configuration.

		clamity os check

	Set a config parameter, in this case CLAMITY_verbose, in the current
	shell only.

		clamity config set verbose 1

	Same as above but set it as a default. It will also have affect for
	all other shells when you run clamity commands. Default settings are
	stored in \$CLAMITY_HOME/defaults.env.

		clamity config set default verbose 1
"
# ---------------------------------------------------------------------------

[ -z "$1" ] && _brief_usage "" "clamity" || _usage "" "clamity" help
exit 1
